[package]
name = "pqcrypto-internals"
description = "Provides safe API functions to the PQCRYPTO traits"
version = "0.2.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
repository = "https://github.com/rustpq/pqcrypto/"
license = "CC0-1.0"

[dependencies]
rand = "0.5.0"
libc = "0.1.0"
sha2 = "0.8.0"
sha3 = "0.8.0"
digest = "0.8.0"

[features]
default = ["asm"]
asm = ["sha2/asm"]

[lib]
crate-type=["staticlib", "cdylib"]
